### ISSUE TITLE
Problem when using __file__

### ISSUE THREAD

**Issue by michaden18** [FXTD-ODYSSEY/vscode-mayapy#1]
Hello, i found a bug when i try to find a path for my file using os.path.abspath(os.__ file __). it work perfectly when i using terminal, but i notice this package will run the script from Local/Temp folder...so, might be become a problem?

# Error: line 1: NameError: file C:/Users/*****/AppData/Local/Temp/MayaCode.py line 6: name '__file__' is not defined #

![Capture](https://user-images.githubusercontent.com/54364466/71558757-e6dfa200-2a99-11ea-94b6-92be3d2d1792.PNG)

**Comment by FXTD-ODYSSEY** [comment]
Thanks for your Bug Reporting.
I try to run your code to hit the same error.
however, I run the code in Maya2019 | Maya2018 | Maya2017.
They both work fine without any problems.

![test](https://user-images.githubusercontent.com/40897360/71589792-12798f80-2b61-11ea-80b8-6b03a260c6cc.png)

Maybe you should open the temp folder MayaCode.py to check the python code there.

You also can try to delete the MayaCode.py file.
The extension will automatically generate a same file.

here is the correct MayaCode.py code run in my machine

```python
# -*- coding: utf-8 -*-

current_directory = r"d:\Users\82047\Desktop"
if current_directory not in sys.path:
	sys.path.insert(0,current_directory)

print("\nMayaPy Python Debugger : debug test module\n")
if 'test' not in globals():
	import test
else:
	reload(test)

```

**Comment by michaden18** [comment]
thank you for your response. my MayaCode.py in temp folder is exactly the same like what i write in test.py  . so maybe that's the reason why it losing the connection using __ file __.

this is MayaCode.py
```
# -*- coding: utf-8 -*-
import os
path = os.path.abspath(__file__)
print(path)
```

for example if i change my test.py into :

```
from maya import cmds
cmds.polyCube()
```
the MayaCode.py will generate the newest code i execute. (the cmds.polyCube()'s version)

**Comment by FXTD-ODYSSEY** [comment]
That's weird.
MayaCode.py should not just copy the code into the py file.
Because that would not trigger the ptvsd python debug module.(only import would make it work)
I guess you are using the MayaCode  extension send to maya feature not the MayaPy extension debug feature.

![image](https://user-images.githubusercontent.com/40897360/71606227-0f56c180-2baa-11ea-904b-75b7465f11e1.png)

**Comment by michaden18** [comment]
i see! yeah i think it happen because i'm using "Send Python Code to Maya". thank you!
