### ISSUE TITLE
我尝试将VSCODE重新删除了所有配置，突然无法自动补全

### ISSUE THREAD

**Issue by DuoLonAsh** [FXTD-ODYSSEY/vscode-mayapy#2]
原先是可以自动补全，过了段时间于今日（2020.1.19）使用
突然无法补全，包括我自身重新采用Python.autoComplete.extraPaths去修改DEVKIT路径上都无法使用。请问是否有什么原因导致？

我使用的是Conda

**Comment by FXTD-ODYSSEY** [comment]
你有没有试过手动触发补全的效果

**Comment by DuoLonAsh** [comment]
> 你有没有试过手动触发补全的效果

我尝试研究一下。

**Comment by DuoLonAsh** [comment]
我尝试更改了触发补全快捷键，显示无建议

**Comment by FXTD-ODYSSEY** [comment]
你是用什么 python 编译器的，用 mayapy.exe 自带的可能不行

**Comment by FXTD-ODYSSEY** [comment]
建议更新一下 Python Extension 试试
